//
//  CoinsListViewController.swift
//  MarketCoins
//
//  Created by Rodrigo Alves Moreira on 19/10/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//

import UIKit

protocol CoinsListDisplayLogic where Self: UIViewController {
  
  func displayViewModel(_ viewModel: CoinsListModel.ViewModel)
}

final class CoinsListViewController: UIViewController {
  
  typealias CoinsListFactory = CoinsListInteractorFactorable & CoinsListRouterFactorable

  private let mainView: CoinsListView
  private var interactor: CoinsListInteractable!
  private var router: CoinsListRouting!
  
  required init(factory: CoinsListFactory, mainView: CoinsListView, dataSource: CoinsListModel.DataSource) {
    self.mainView = mainView
    
    super.init(nibName: nil, bundle: nil)
    
    let interactorFactory = factory as! CoinsListInteractorFactorable.InteractableFactory
    interactor = factory.makeInteractor(factory: interactorFactory, viewController: self, dataSource: dataSource)
    router = factory.makeRouter(viewController: self)
  }
  
  override func viewDidLoad() {
    super.viewDidLoad()
    //interactor.doSomething(item: 22)
  }
  
  override func loadView() {
    mainView.delegate = self
    view = mainView
  }

  @available(*, unavailable)
  required init?(coder: NSCoder) {
    fatalError("init(coder:) has not been implemented, You shouldn't initialize the ViewController using Storyboards")
  }
}

// MARK: - CoinsListDisplayLogic
extension CoinsListViewController: CoinsListDisplayLogic {

  func displayViewModel(_ viewModel: CoinsListModel.ViewModel) {
    DispatchQueue.main.async {
      switch viewModel {

      case .doSomething(let viewModel):
        self.displayDoSomething(viewModel)
      }
    }
  }
}


// MARK: - CoinsListViewDelegate
extension CoinsListViewController: CoinsListViewDelegate {
  
  func sendDataBackToParent(_ data: Data) {
    //usually this delegate takes care of user actions and requests through UI
    
    //do something with the data or message sent back from mainView
  }
}


// MARK: - Private Zone
private extension CoinsListViewController {
  
  func displayDoSomething(_ viewModel: NSObject) {
    print("Use the mainView to present the viewModel")
    //example of using router
    router.routeTo(.xScene(xData: 22))
  }
}
