//
//  CoinsListPresenter.swift
//  MarketCoins
//
//  Created by Rodrigo Alves Moreira on 19/10/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//

import Foundation

protocol CoinsListPresentationLogic {
  func presentResponse(_ response: CoinsListModel.Response)
}

final class CoinsListPresenter {
  private weak var viewController: CoinsListDisplayLogic?
  
  init(viewController: CoinsListDisplayLogic?) {
    self.viewController = viewController
  }
}


// MARK: - CoinsListPresentationLogic
extension CoinsListPresenter: CoinsListPresentationLogic {
  
  func presentResponse(_ response: CoinsListModel.Response) {
    
    switch response {
      
    case .doSomething(let theNewItem, let isItem):
      presentDoSomething(theNewItem, isItem)
    }
  }
}


// MARK: - Private Zone
private extension CoinsListPresenter {
  
  func presentDoSomething(_ newItem: Int, _ isItem: Bool) {
    
    //prepare data for display and send it further
    
    viewController?.displayViewModel(.doSomething(viewModelData: NSObject()))
  }
}
